//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPhoto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uPhotoEntities : DbContext
    {
        public uPhotoEntities()
            : base("name=uPhotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<album> album { get; set; }
        public DbSet<comentario> comentario { get; set; }
        public DbSet<etiqueta> etiqueta { get; set; }
        public DbSet<fotografia> fotografia { get; set; }
        public DbSet<fotografo> fotografo { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<publicacion> publicacion { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<rolporusuario> rolporusuario { get; set; }
        public DbSet<sesion> sesion { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<foro> foro { get; set; }
        public DbSet<fotosporfotografo> fotosporfotografo { get; set; }
        public DbSet<perfil> perfil { get; set; }
    }
}
