//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etiqueta
    {
        public etiqueta()
        {
            this.album = new HashSet<album>();
            this.publicacion = new HashSet<publicacion>();
        }
    
        public string nombreetiqueta { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<album> album { get; set; }
        public virtual ICollection<publicacion> publicacion { get; set; }
    }
}
