//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foro
    {
        public System.DateTime fechacreacion { get; set; }
        public int idusuario { get; set; }
        public string publicacion { get; set; }
        public string nombreetiqueta { get; set; }
    }
}
