//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotografia
    {
        public fotografia()
        {
            this.comentario = new HashSet<comentario>();
            this.album = new HashSet<album>();
        }
    
        public int idfotografia { get; set; }
        public string titulo { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public string descripcion { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual ICollection<album> album { get; set; }
    }
}
