//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotografo
    {
        public fotografo()
        {
            this.album = new HashSet<album>();
        }
    
        public int idusuario { get; set; }
        public string nombrerol { get; set; }
        public string emailcontacto { get; set; }
        public Nullable<System.DateTime> tiempoexperiencia { get; set; }
    
        public virtual rolporusuario rolporusuario { get; set; }
        public virtual ICollection<album> album { get; set; }
    }
}
