//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int idproducto { get; set; }
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> fechalanzamiento { get; set; }
        public System.DateTime fecharegistro { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
