//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        public publicacion()
        {
            this.comentario = new HashSet<comentario>();
            this.etiqueta = new HashSet<etiqueta>();
        }
    
        public int idpublicacion { get; set; }
        public int idusuario { get; set; }
        public string publicacion1 { get; set; }
        public byte[] foto { get; set; }
        public System.DateTime fechacreacion { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual ICollection<etiqueta> etiqueta { get; set; }
    }
}
