//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPhoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol
    {
        public rol()
        {
            this.rolporusuario = new HashSet<rolporusuario>();
        }
    
        public string nombrerol { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
    
        public virtual ICollection<rolporusuario> rolporusuario { get; set; }
    }
}
